### PR TITLE
Fix broken coding standard path.

### PR DESCRIPTION
**Pull request by dmolineus**

### CODE REVIEW

**Comment by discordier** [comment]
Nice catch

**Comment by dmolineus** [comment]
We definitely should. Doing some improvements on phpcq is on my todo list for a long time... I actually switched to doctrine/coding-standard for recent projects which I pretty like.

If we start modernizing our coding standard we could have a look on docrine/coding-standards - though it has a different approach as it do not force do add docs for everything - it has some nice improvements for type declarations and documentation.

**Comment by discordier** [comment]
Forcing doc blocks is a quite controversial topic.
I dislike the current habit of "throw away all doc blocks" among the PHP ecosystem.

I agree that forcing them on everything is not perfect from a view of "code noise" but I think it is still better than having too less blocks.

I encounter more and more libraries where they are missing and I simply have no clue how the classes fit together and have to dig the code. Going back some versions where there were blocks, there was information which got deleted.

Granted, simple setter and getter comments are not that useful on their own.

**Comment by dmolineus** [comment]
> Forcing doc blocks is a quite controversial topic.
> I dislike the current habit of "throw away all doc blocks" among the PHP ecosystem.

Agree, a coding standard should at leas encourage people to add doc blocks. 

> I agree that forcing them on everything is not perfect from a view of "code noise" but I think it is still better than having too less blocks.

I accept that doc blocks are required. As PHP is moving more and more to a typed language some docs which are currently required in the cca coding standard are superflous in my point of view:

 - Forced `@return` types if a method has defined return type
 - Descriptions for class properties which are self describing by it's type annotation

**Comment by discordier** [comment]
For the return types and parameter types I agree.

But they should have some note of the purpose - like what is it good for.

**Pull request merged**
